version: 2
before:
  hooks:
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
  goos:
    - freebsd
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - '386'
    - arm
    - arm64
  goarm:
    - '7'
  ignore:
    - goos: darwin
      goarch: '386'
    - goos: windows
      goarch: arm
  binary: '{{ .ProjectName }}_v{{ .Version }}'
archives:
- files: []
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      # if you are using this in a GitHub action or some other automated pipeline, you 
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  github:
    owner: leefowlercu
    name: terraform-provider-contextforge
  draft: true
  replace_existing_draft: true
  prerelease: auto
  header: |
    ## Installation

    To use this provider, add the following to your Terraform configuration:

    ```hcl
    terraform {
      required_providers {
        contextforge = {
          source  = "hashicorp/contextforge"
          version = "~> {{ .Version }}"
        }
      }
    }
    ```

    See the [provider documentation](https://registry.terraform.io/providers/hashicorp/contextforge/latest/docs) for usage details.
  footer: |
    **Full Changelog**: https://github.com/leefowlercu/terraform-provider-contextforge/compare/{{ .PreviousTag }}...{{ .Tag }}
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
changelog:
  use: git
  sort: asc
  abbrev: 7
  groups:
    - title: Added
      regexp: '^feat:'
      order: 0
    - title: Fixed
      regexp: '^(fix|bug):'
      order: 1
    - title: Changed
      regexp: '^refactor:'
      order: 2
    - title: Documentation
      regexp: '^docs:'
      order: 3
    - title: Build
      regexp: '^(build|chore):'
      order: 4
    - title: Tests
      regexp: '^(test|style):'
      order: 5
  # Exclude release preparation commits
  filters:
    exclude:
      - '^release: prepare v'
      - '^docs: update changelog'
      - Merge pull request
      - Merge branch
